umd-lib/student-applications

app/views/prospects/_work_experience_step.html.erb
db/migrate/20161021173906_add_more_fields_to_work_experiences.rb
db/schema.rb
test/features/work_experiences_test.rb

This adds dates of employment, location, duties, and a "Is this Library Related?"
toggle.
https://issues.umd.edu/browse/LIBITD-541

LIBITD-541 Add additional fields to Work Experience

---

app/assets/javascripts/prospect.js
app/assets/stylesheets/application.css
app/helpers/application_helper.rb
app/views/prospects/_availability_step.html.erb

Only availability table in the availabilty step should respond to hover CSS
selector.
https://issues.umd.edu/browse/LIBITD-600

LIBITD-600 Remove hover from availability table in confirmation step

---

app/mailers/submitted_mailer.rb
app/views/submitted_mailer/default_email.html.erb
app/views/submitted_mailer/default_email.text.erb

Updates the default email text when there is a submission.
https://issues.umd.edu/browse/LIBITD-599

LIBITD-599 Update email boilerplate

---

app/controllers/application_controller.rb
app/models/user.rb
db/migrate/20161207205622_create_users.rb
db/schema.rb
lib/tasks/add_cas_user.rake
test/fixtures/users.yml
test/models/user_test.rb

If the user doesn't exist, deny access.
https://issues.umd.edu/browse/LIBITD-641

LIBITD-641. Check authenticated CAS user ID against user model.

---

app/controllers/prospects_controller.rb
app/views/prospects/new.html.erb

The new controller also resets the session.
https://issues.umd.edu/browse/LIBITD-648

LIBITD-648. Added "Reset" button.

---

app/assets/stylesheets/application.css
app/views/prospects/_skill_fields.html.erb

Sized fields on the prospect form appropriately. Cleaned up some border and margin issues.
https://issues.umd.edu/browse/LIBITD-649

LIBITD-649. CSS cleanup.

---

app/controllers/prospects_controller.rb
app/models/prospect.rb
app/views/prospects/_contact_info_step.html.erb
app/views/prospects/_summary.html.erb
db/migrate/20161209153023_add_semester_to_prospects.rb
db/schema.rb

https://issues.umd.edu/browse/LIBITD-653

LIBITD-653. Added semester field.

---

.gitignore
Gemfile
Gemfile.lock
README.md

Also made some minor changes to the Gemfile (to fix rubocop warnings), small updates to the
README.md to expand the setup instructions, and added the NetBeans workspace to .gitignore.
https://issues.umd.edu/browse/LIBITD-662

LIBITD-662. Add server environment banner to student-application

---

app/assets/javascripts/configuration.js
app/assets/javascripts/prospect.js
app/assets/javascripts/user.js
app/assets/stylesheets/application.css
app/controllers/application_controller.rb
app/controllers/configuration_controller.rb
app/controllers/home_controller.rb
app/controllers/prospects_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/enumeration.rb
app/views/configuration/show.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
app/views/prospects/_summary.html.erb
app/views/prospects/new.html.erb
app/views/users/index.html.erb
config/routes.rb
db/migrate/20161214065805_add_admin.rb
db/schema.rb
lib/tasks/add_cas_user.rake
test/models/user_test.rb

This adds the ability for specific users to log in and view/edit records.
https://issues.umd.edu/browse/LIBITD-579

LIBITD-579 Add admin functionality

---

Gemfile.lock
app/assets/javascripts/prospect.js
app/assets/javascripts/review_applications.js
app/assets/stylesheets/application.css
app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/prospects_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/enumeration.rb
app/models/prospect.rb
app/views/prospects/_availability_modal.html.erb
app/views/prospects/index.html.erb
config/routes.rb
lib/tasks/add_cas_user.rake
test/features/availability_test.rb
test/models/user_test.rb

This add some basic formating to the index pages for admins and non-admins.
Essentiall sets the default columns used.
Still need to add search and sorting.
https://issues.umd.edu/browse/LIBITD-643
https://issues.umd.edu/browse/LIBITD-642

LIBITD-642 and LIBITD-643

---

app/controllers/application_controller.rb
app/controllers/resumes_controller.rb
test/controllers/resume_controller_test.rb
test/fixtures/users.yml

This allows auth'ed users to download resumes.
https://issues.umd.edu/browse/LIBITD-672

LIBITD-672 Allow authed users to download resumes

---

README.md
app/assets/stylesheets/application.css
app/helpers/application_helper.rb

Adds some chevrons.
https://issues.umd.edu/browse/LIBITD-642

LIBITD-642 CSS improvements for sorting

---

Gemfile
app/controllers/concerns/querying_prospects.rb
app/models/prospect.rb
config/initializers/assets.rb
db/seeds.rb
db/seeds/demo.rb

This fixes a few things that come up  when using PG

Some fixes for postgres

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
test/features/admin_disable_test.rb
test/features/prospect_deactivate_test.rb
test/features/reset_form_test.rb

Removes "Staff Sign-In" link from home page.
https://issues.umd.edu/browse/LIBITD-679

LIBITD-679. Remove "Staff Sign-In" link from Student Applications home page

---

app/assets/javascripts/prospects_index.js
app/assets/stylesheets/application.css
app/controllers/concerns/querying_prospects.rb
app/controllers/prospects_controller.rb
app/views/prospects/_filter_modal.html.erb
test/features/filter_available_hours_test.rb
vendor/assets/javascripts/bootstrap-slider.js
vendor/assets/stylesheets/bootstrap-slider.css

This adds a available hours per week scroll bar filter to allow filtering of
max and min available hours per week
Also move the semester filter above the skills selector.
https://issues.umd.edu/browse/LIBITD-682
https://issues.umd.edu/browse/LIBITD-689

LIBITD-673, LIBITD-689 Add available hours per week filter

---

app/assets/stylesheets/application.css

Displays on both the form and the summary page.
https://issues.umd.edu/browse/LIBITD-681

LIBITD-681. Added check mark to selected hours.

---

app/views/prospects/_summary.html.erb

https://issues.umd.edu/browse/LIBITD-683

LIBITD-683. Show addresses and phone numbers to all logged in users.

---

app/assets/stylesheets/application.css
app/controllers/resumes_controller.rb
app/views/prospects/_resume_uploader.html.erb
app/views/prospects/_summary.html.erb
app/views/resumes/_form.html.erb
app/views/resumes/edit.html.erb

Created an edit method in the resume controller and an edit view. The edit view shares the resume uploader partial with the new prospect resume uploader step. Added logic that changes which form the prospect summary links to based on whether it is being shown to an applicant or to an admin user.
https://issues.umd.edu/browse/LIBITD-686

LIBITD-686. Added a resume edit form.

---

app/controllers/concerns/querying_prospects.rb

https://issues.umd.edu/browse/LIBITD-685

LIBITD-685. Do a case-insensitive sort when sorting on last name.

---

app/helpers/application_helper.rb
test/features/sort_preserves_filter_test.rb

This preserves the existing filter query parameters, just adds or replaces the sort and direction parameters.
https://issues.umd.edu/browse/LIBITD-675

LIBITD-675. Merge in sort parameters to column header link.

---

Gemfile
Gemfile.lock

Also added a custom :github git_source that uses HTTPS URLs for GitHub repos.
https://issues.umd.edu/browse/LIBITD-707

LIBITD-707. Upgrade to umd_lib_style 0.2.0.

---

app/controllers/prospects_controller.rb
app/models/phone_number.rb
app/models/prospect.rb
app/views/prospects/_phone_number_fields.html.erb
test/features/availability_test.rb
test/features/comment_confirmation_test.rb
test/features/contact_information_test.rb
test/features/end_to_end_test.rb
test/fixtures/phone_numbers.yml
test/integration/submit_prospect_application_test.rb
test/models/prospect_test.rb

https://issues.umd.edu/browse/LIBITD-690

LIBITD-690. Require phone number.

---

app/controllers/concerns/querying_prospects.rb
app/controllers/prospects_controller.rb
app/views/prospects/_filter_modal.html.erb
test/features/filter_available_times_test.rb

Note: The feature test for this has been failing intermittently for me on my workstation due to delays between when Capybara executes the `check` or `click` commands to manipulate form elements and when those manipulations appear in the live DOM.
https://issues.umd.edu/browse/LIBITD-674

LIBITD-674. Added option to filter by available times.

---

app/controllers/prospects_controller.rb
app/views/prospects/index.html.erb
test/controllers/prospects_controller_test.rb
test/features/filter_available_times_test.rb
test/features/filter_class_status_test.rb
test/models/prospect_test.rb

This catches and submission failures on save attempts ( either via ActiveRecord
issues or ActionMailer problems ) and adds some additional logging.
Also some minor tweaks to some capybara tests to tamp down on itermittent
failures due to AJAX.
https://issues.umd.edu/browse/LIBITD-723

LIBITD-723 Add additional logging for submission failures

---

README.md
lib/tasks/add_cas_user.rake

Adds a rake task that allows you to point at a Name, CAS ID csv file to bulk
add users.
LIBITD-729

LIBITD-729 Add bulk update for user data using a CSV

---

app/assets/stylesheets/application.scss
app/controllers/prospects_controller.rb
app/views/prospects/_pagination.html.erb
app/views/prospects/index.html.erb

This:
* Adds a "showing ## applications of ##" message to pagination
* Adds a pagination section to top of prospects#index table
* Pulls pagination sections right
https://issues.umd.edu/browse/LIBITD-730

LIBITD-730 Add record count to  pagnization on prospects#index page

---

app/assets/javascripts/id_and_semester.js
app/controllers/prospects_controller.rb
app/models/concerns/walkable.rb
app/models/prospect.rb
app/views/prospects/_contact_info_step.html.erb
app/views/prospects/_id_and_semester_step.html.erb
app/views/prospects/_skill_fields.html.erb
app/views/prospects/_summary.html.erb
app/views/prospects/edit.html.erb
db/migrate/20170207065805_add_id_semester_uniq.rb
db/schema.rb
db/seeds/demo.rb
test/controllers/prospects_controller_test.rb
test/features/availability_test.rb
test/features/comment_confirmation_test.rb
test/features/contact_information_test.rb
test/features/end_to_end_test.rb
test/features/reset_form_test.rb
test/features/resume_upload_test.rb
test/integration/submit_prospect_application_test.rb
test/models/prospect_test.rb
test/test_helper.rb

Only allow one active application based on directory_id and semester ( students cannot apply multiple times per semester ) 
https://issues.umd.edu/browse/LIBITD-734

LIBITD-734 Block submission based on directory_id and semester

---

app/views/prospects/_filter_modal.html.erb
test/features/filter_directory_id_test.rb

This adds a directory_id to the filter on the admin UI.
https://issues.umd.edu/browse/LIBITD-759

LIBITD-759 Add filter by directory_id to admin ui

---

README.md

This adds documentation on the delayed job rake tasks.
https://issues.umd.edu/browse/LIBITD-1082

LIBITD-1082 Add more documentation about delayed_job options

---

Dockerfile.ci
Jenkinsfile
README.md
test/application_system_test_case.rb

Updated "Jenkinsfile" to use "Dockerfile.ci" image for building and
testing the application.
Added information about "Dockerfile.ci" and "Jenkinsfile" to README.md.
https://issues.umd.edu/browse/LIBITD-1486

LIBITD-1486. Initial implementation of Docker-based Jenkins build
